import { Metadata } from "next";
import { HomeTemplate } from "./components/templates/HomeTemplate";

export const metadata: Metadata = {
  title: "ToDo App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <HomeTemplate />
    </>
  );
}
